POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl" : "https://stackoverflow.com/questions/66660081/fatal-no-pg-hba-conf-entry-error-from-postgres-using-db-migrate-in-node-on-he?noredirect=1&lq=1"
}
